### ISSUE TITLE
Respuesta duda modelado

### ISSUE THREAD

**Issue by josibuttazzoni** [scupolo/Paradigmas-#12]
https://github.com/scupolo/Paradigmas-/blob/fd6ba4366dc269e110412b1949654274cca8deee/sofiama%C3%B1ana.hs#L29

¡En ambos casos es por lo mismo! Tenés que pasarle todos los parámetros para que te "cree" a tu jugador. Entonces en el caso de declararla de esa forma, seria así:

`carolina = Jugador { nombreDelJugador = "Carolina", cantDinero = 500, tacticaJugador = "Accionista",  propiedadesAdquiridas = [], accionesJugador = [pagarAAccionistas, pasarPorElBanco] }`

**Comment by scupolo** [comment]
sisi se entendió perfecto, ahí volví a subir las correcciones de los issues

**Comment by josibuttazzoni** [comment]
Bárbaro, Sofi. Ahora lo miro bien y cualquier cosa te dejo más issues
