### ISSUE TITLE
Se puede mejorar un poco más todavía 

### ISSUE THREAD

**Issue by josibuttazzoni** [scupolo/Paradigmas-#13]
La idea era que cambiarDinero fuera una función que reciba al jugador y al monto de dinero y te devolviera al nuevo jugador, con el monto modificado. Y que hicieras lo mismo para el resto de las acciones, por ejemplo, cambiar táctica, agregar propiedad, etc. Fijate que ademas, si lo haces asi, podes aprovechar y usar composición.

```haskell
cambiarDinero :: Int -> Jugador -> Jugador
cambiarDinero unMonto unJugador = unJugador { dinero = dinero unJugador + unMonto }

cambiarTactica :: String -> Jugador -> Jugador
cambiarTactica unaTactica unJugador = persona { tactica = unaTactica }

pasarPorElBanco unJugador = cambiarDinero 40 . cambiarTactica "Comprador compulsivo" $ unJugador
```

**Comment by scupolo** [comment]
josi ahi modifique algunos issues que me mencionaste, el tema es que me esta costando modificar estas funciones porque se me rompe la funcion cobrarAlquileres donde uso cambiarDinero  ( cantidadDinero) y no se como modificarla.

**Comment by josibuttazzoni** [comment]
Perfecto lo que corregiste, sofi! Por que decís que te rompe cobrarAlquileres? Usando cambiarDinero debería quedar algo así:
```haskell
cobrarAlquileres :: Accion
cobrarAlquileres unJugador = cambiarDinero (precioDelAlquiler.propiedadesAdquiridas $unJugador) unJugador
```

**Comment by scupolo** [comment]
buenisimo josi, ahí subí las nuevas modificaciones. Pude arreglar la función cobrarAlquileres sin que se me rompa, pero igual puso como opción la tuya, y deje en comentario la otra.

**Comment by josibuttazzoni** [comment]
Geniall, sofi! Quedo todo re bien🙌
